@VehicleTrackingSystem_HostAddress = http://localhost:5030

GET {{VehicleTrackingSystem_HostAddress}}/api/providers
Accept: application/json

###

GET {{VehicleTrackingSystem_HostAddress}}/api/providers/1
Accept: application/json

###

GET {{VehicleTrackingSystem_HostAddress}}/api/providers/1/field-mappings
Accept: application/json

###

GET {{VehicleTrackingSystem_HostAddress}}/api/vehicle-types
Accept: application/json

###

GET {{VehicleTrackingSystem_HostAddress}}/api/vehicle-types/1
Accept: application/json

###

GET {{VehicleTrackingSystem_HostAddress}}/api/vehicle-types/GARBAGE_TRUCK/provider
Accept: application/json

###

GET {{VehicleTrackingSystem_HostAddress}}/api/vehicles
Accept: application/json

###

GET {{VehicleTrackingSystem_HostAddress}}/api/vehicles/34%20ITF%20101
Accept: application/json

###
