using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VehicleTrackingSystem.Data;

#nullable disable

namespace VehicleTrackingSystem.Migrations.PostgreSql
{
    /// <inheritdoc />
    [DbContext(typeof(PostgreSqlVehicleTrackingDbContext))]
    [Migration("20260818183500_AddFacilitiesRoutingGeometry")]
    public partial class AddFacilitiesRoutingGeometry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS postgis;");

            migrationBuilder.Sql("""
                CREATE TABLE facilities (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name character varying(150) NOT NULL,
                    code character varying(50) NOT NULL,
                    facility_type character varying(50) NOT NULL,
                    location geometry(Point, 4326) NOT NULL,
                    boundary geometry(Polygon, 4326) NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE destinations (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name character varying(200) NOT NULL,
                    location geometry(Point, 4326) NOT NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE route_requests (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    vehicle_plate character varying(50) NULL,
                    provider_code character varying(50) NULL,
                    from_facility_id integer NOT NULL REFERENCES facilities(id) ON DELETE RESTRICT,
                    to_destination_id integer NULL REFERENCES destinations(id) ON DELETE SET NULL,
                    to_latitude double precision NOT NULL,
                    to_longitude double precision NOT NULL,
                    requested_at timestamp with time zone NOT NULL
                );
                """);

            migrationBuilder.Sql("CREATE UNIQUE INDEX ix_facilities_code ON facilities(code);");
            migrationBuilder.Sql("CREATE INDEX ix_facilities_location_gist ON facilities USING GIST(location);");
            migrationBuilder.Sql("CREATE INDEX ix_facilities_boundary_gist ON facilities USING GIST(boundary);");

            migrationBuilder.Sql("""
                INSERT INTO facilities (name, code, facility_type, location, boundary)
                VALUES (
                    'Kocaeli Merkez Itfaiye',
                    'FIRE_STATION_001',
                    'FIRE_STATION',
                    ST_SetSRID(ST_MakePoint(29.940000, 40.765000), 4326),
                    ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[[29.936,40.762],[29.944,40.762],[29.944,40.768],[29.936,40.768],[29.936,40.762]]]}'), 4326)
                );
                """);

            migrationBuilder.Sql("""
                INSERT INTO destinations (name, location)
                VALUES
                    ('A Mahallesi B Caddesi', ST_SetSRID(ST_MakePoint(29.955000, 40.772000), 4326)),
                    ('Merkez Meydani', ST_SetSRID(ST_MakePoint(29.946000, 40.766000), 4326)),
                    ('Sanayi Sitesi', ST_SetSRID(ST_MakePoint(29.920000, 40.758000), 4326));
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS route_requests;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS destinations;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS facilities;");
        }
    }
}
