using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VehicleTrackingSystem.Data;

#nullable disable

namespace VehicleTrackingSystem.Migrations.Oracle
{
    /// <inheritdoc />
    [DbContext(typeof(OracleVehicleTrackingDbContext))]
    [Migration("20260818183500_AddFacilitiesRoutingGeometry")]
    public partial class AddFacilitiesRoutingGeometry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE facilities (
                    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    name NVARCHAR2(150) NOT NULL,
                    code NVARCHAR2(50) NOT NULL,
                    facility_type NVARCHAR2(50) NOT NULL,
                    location SDO_GEOMETRY NOT NULL,
                    boundary SDO_GEOMETRY NULL
                )
                """);

            migrationBuilder.Sql("""
                CREATE TABLE destinations (
                    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    name NVARCHAR2(200) NOT NULL,
                    location SDO_GEOMETRY NOT NULL
                )
                """);

            migrationBuilder.Sql("""
                CREATE TABLE route_requests (
                    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    vehicle_plate NVARCHAR2(50) NULL,
                    provider_code NVARCHAR2(50) NULL,
                    from_facility_id NUMBER(10) NOT NULL,
                    to_destination_id NUMBER(10) NULL,
                    to_latitude BINARY_DOUBLE NOT NULL,
                    to_longitude BINARY_DOUBLE NOT NULL,
                    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    CONSTRAINT fk_route_requests_facilities
                        FOREIGN KEY (from_facility_id) REFERENCES facilities(id),
                    CONSTRAINT fk_route_requests_destinations
                        FOREIGN KEY (to_destination_id) REFERENCES destinations(id)
                )
                """);

            migrationBuilder.Sql("CREATE UNIQUE INDEX ix_facilities_code ON facilities(code)");

            migrationBuilder.Sql("""
                INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
                VALUES (
                    'FACILITIES',
                    'LOCATION',
                    SDO_DIM_ARRAY(
                        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
                        SDO_DIM_ELEMENT('Latitude', -90, 90, 0.005)
                    ),
                    4326
                )
                """);

            migrationBuilder.Sql("""
                INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
                VALUES (
                    'FACILITIES',
                    'BOUNDARY',
                    SDO_DIM_ARRAY(
                        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
                        SDO_DIM_ELEMENT('Latitude', -90, 90, 0.005)
                    ),
                    4326
                )
                """);

            migrationBuilder.Sql("""
                INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
                VALUES (
                    'DESTINATIONS',
                    'LOCATION',
                    SDO_DIM_ARRAY(
                        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
                        SDO_DIM_ELEMENT('Latitude', -90, 90, 0.005)
                    ),
                    4326
                )
                """);

            migrationBuilder.Sql("CREATE INDEX ix_facilities_location_spatial ON facilities(location) INDEXTYPE IS MDSYS.SPATIAL_INDEX");
            migrationBuilder.Sql("CREATE INDEX ix_facilities_boundary_spatial ON facilities(boundary) INDEXTYPE IS MDSYS.SPATIAL_INDEX");
            migrationBuilder.Sql("CREATE INDEX ix_destinations_location_spatial ON destinations(location) INDEXTYPE IS MDSYS.SPATIAL_INDEX");

            migrationBuilder.Sql("""
                INSERT INTO facilities (name, code, facility_type, location, boundary)
                VALUES (
                    'Kocaeli Merkez Itfaiye',
                    'FIRE_STATION_001',
                    'FIRE_STATION',
                    SDO_UTIL.FROM_GEOJSON('{"type":"Point","coordinates":[29.94,40.765]}'),
                    SDO_UTIL.FROM_GEOJSON('{"type":"Polygon","coordinates":[[[29.936,40.762],[29.944,40.762],[29.944,40.768],[29.936,40.768],[29.936,40.762]]]}')
                )
                """);

            migrationBuilder.Sql("""
                INSERT INTO destinations (name, location)
                VALUES ('A Mahallesi B Caddesi', SDO_UTIL.FROM_GEOJSON('{"type":"Point","coordinates":[29.955,40.772]}'))
                """);

            migrationBuilder.Sql("""
                INSERT INTO destinations (name, location)
                VALUES ('Merkez Meydani', SDO_UTIL.FROM_GEOJSON('{"type":"Point","coordinates":[29.946,40.766]}'))
                """);

            migrationBuilder.Sql("""
                INSERT INTO destinations (name, location)
                VALUES ('Sanayi Sitesi', SDO_UTIL.FROM_GEOJSON('{"type":"Point","coordinates":[29.92,40.758]}'))
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE route_requests");
            migrationBuilder.Sql("DROP TABLE destinations");
            migrationBuilder.Sql("DROP TABLE facilities");
            migrationBuilder.Sql("DELETE FROM user_sdo_geom_metadata WHERE table_name IN ('FACILITIES', 'DESTINATIONS')");
        }
    }
}
